config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'users/index', to: 'users#index'
  root 'minirooms#index'
  # resources :users, only: [:new, :show]
  resources :users do
      resource :relationships, only: [:create, :destroy]
      get :followings, on: :member
      get :followers, on: :member
  end

  resources :minirooms do
  resource :miniroomfavorites, only: [:create, :destroy]
  resources :miniroomcomments, only: :create
  collection do
    get 'search'
  end
  end

  resources :donations do
    resources :receives, only: [:index, :new, :create]
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :minirooms, dependent: :destroy
  has_many :donations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_donations, through: :favorites, source: :donation
  has_many :miniroomfavorites, dependent: :destroy
  has_many :miniroomfavorited_minirooms, through: :miniroomfavorites, source: :miniroom

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
   { user: user, sns: sns }
  end

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
   validates :firstname
   validates :lastname
  end

  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
   end
  
   def google_oauth2
    authorization
   end
  
   private
  
   def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

   if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
    sign_in_and_redirect @user, event: :authentication
  else #ユーザー情報が未登録なので、新規登録画面へ遷移する
    @sns_id = sns_info[:sns].id
    render template: 'devise/registrations/new'
  end
end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def show
    @user = User.find(params[:id])
    @donations = @user.donations
    @minirooms = @user.minirooms
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>ニックネーム</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.nickname %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger", style="background-color:#da6666;">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>ニックネーム</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.nickname %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger", style="background-color:#da6666;">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <table class="table text-center">
        <thead>
          <tr>
            <th>ニックネーム</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.nickname %>
                <% end %>
              </td>
              <td>
                <% if user.is_followed_by?(current_user) %>
                  <%=link_to user_relationships_path(user), method: :delete do %>
                    <button type="button" class="btn btn-danger", style="background-color:#da6666;">フォロー解除</button>
                  <% end %>
                <% else %>
                  <%=link_to user_relationships_path(user), method: :post do %>
                    <button type="button" class="btn btn-primary">フォロー</button>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= link_to "メールアドレスで登録", new_user_registration_path%>
<%= link_to "Facebookで登録", user_facebook_omniauth_authorize_path, method: :post%>
<%= link_to "Googleで登録", user_google_oauth2_omniauth_authorize_path, method: :post%>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <svg width="80" height="80" class="svg-icon" viewBox="0 0 20 20">
            <path d="M12.075,10.812c1.358-0.853,2.242-2.507,2.242-4.037c0-2.181-1.795-4.618-4.198-4.618S5.921,4.594,5.921,6.775c0,1.53,0.884,3.185,2.242,4.037c-3.222,0.865-5.6,3.807-5.6,7.298c0,0.23,0.189,0.42,0.42,0.42h14.273c0.23,0,0.42-0.189,0.42-0.42C17.676,14.619,15.297,11.677,12.075,10.812 M6.761,6.775c0-2.162,1.773-3.778,3.358-3.778s3.359,1.616,3.359,3.778c0,2.162-1.774,3.778-3.359,3.778S6.761,8.937,6.761,6.775 M3.415,17.69c0.218-3.51,3.142-6.297,6.704-6.297c3.562,0,6.486,2.787,6.705,6.297H3.415z"></path>
          </svg>
          <h1 class="fw-light"><%= "#{@user.nickname}さんの写真投稿・Donation投稿" %></h1>
          <p class="text-small"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー <%= link_to @user.followers.count, followers_user_path(@user) %> フォロワー</p>
          <% if @user == current_user %>
            <p class="lead text-muted">You're currently signed in as <%= current_user.email %></p><br>
          <% else %>
        <% if @user.is_followed_by?(@user) %>
          <%= link_to user_relationships_path(@user), method: :delete do %>
            <button class="btn btn-danger", style="background-color:#da6666;" >フォロー解除</button><br><br>
          <% end %>
        <% else %>
          <%= link_to user_relationships_path(@user), method: :post do %>
            <button class="btn btn-primary">フォロー</button><br><br>
          <% end %>
        <% end %>
          <% end %>
        </div>
      </div>
    </section>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'donations/donation', collection: @user.donations %>
          <%= render partial: 'minirooms/miniroom', collection: @user.minirooms %>
      </div>
    </div>
  </div>
</div>