config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'users/index', to: 'users#index'
  root 'minirooms#index'
  # resources :users, only: [:new, :show]
  resources :users do
      resource :relationships, only: [:create, :destroy]
      get :followings, on: :member
      get :followers, on: :member
  end

  resources :minirooms do
  resource :miniroomfavorites, only: [:create, :destroy]
  resources :miniroomcomments, only: :create
  collection do
    get 'search'
  end
  end

  resources :donations do
    resources :receives, only: [:index, :new, :create]
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/miniroom.rb
class Miniroom < ApplicationRecord
  validates :title, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  has_one_attached :image
  belongs_to :user
  has_many :miniroomfavorites, dependent: :destroy
  has_many :miniroomfavorited_users, through: :miniroomfavorites, source: :user
  has_many :miniroomcomments, dependent: :destroy

  def self.search(search)
    if search != ""
      Miniroom.where('title LIKE(?)', "%#{search}%")
    else
      Miniroom.all
    end
  end

  def favorited?(user)
    miniroomfavorites.where(user_id: user.id).exists?
 end
end

app/controllers/minirooms_controller.rb
class MiniroomsController < ApplicationController
  before_action :set_miniroom, only: [:edit, :show, :update, :destroy]

  def index
    @minirooms = Miniroom.all.order("created_at DESC")
    @user = User.new
  end

  def new
    @miniroom = Miniroom.new
  end
  
  def create
    @miniroom = Miniroom.new(miniroom_params)
    if @miniroom.save  
    redirect_to root_path
    else
      render :new
    end
  end

  def show
    @miniroomcomment = Miniroomcomment.new
    @miniroomcomments = @miniroom.miniroomcomments.includes(:user)
  end

  def edit
    if user_signed_in? && current_user.id == @miniroom.user_id 
     redirect_to miniroom_path  unless current_user.id == @miniroom.user_id
    else
       redirect_to root_path
    end
  end

  def update
   if @miniroom.update(miniroom_params)
    redirect_to miniroom_path
   else
    render :edit
   end
  end

  def destroy
    if @miniroom.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  def search
    @minirooms = Miniroom.search(params[:keyword])
  end

  private

  def miniroom_params
    params.require(:miniroom).permit(:title, :concept, :image).merge(user_id: current_user.id)
  end

  def set_miniroom 
    @miniroom = Miniroom.find(params[:id])
  end

end

app/helpers/minirooms_helper.rb
module MiniroomsHelper
end

app/views/minirooms/_form.html.erb
<%= form_with model: @miniroom, local: true do |f|%>
<%= render 'layouts/error_messages', model: f.object %>
<div class="minimalist">
  <div class="field">
    <%= f.label :title, "画像のタイトル" %><br />
    <%= f.text_field :title, id:"miniroom_title" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"miniroom_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "ミニマルの画像" %><br />
    <%= f.file_field :image, id:"miniroom_image" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
  </div>
<% end %>

app/views/minirooms/_miniroom.html.erb
<div class="card">
  <div class="card__body">
  <%= link_to image_tag(miniroom.image, class: :card__img ), miniroom_path(miniroom.id), method: :get %><br>

    <%= link_to miniroom.title, minirooms_path(miniroom.id), class: :card__title%><br>
<%= link_to "/#{miniroom.user.nickname}さん", "/users/#{miniroom.user.id}" , class: :card__user %>
 <%# <%= link_to "by #{mini_room.user_id.nickname}", "/users/#{mini_room.user.id}" , class: :card__user %>
  </div>
<p class="pagetop"><a href="#wrap">▲</a></p>
<script>
$(document).ready(function() {
  var pagetop = $('.pagetop');
    $(window).scroll(function () {
       if ($(this).scrollTop() > 100) {
            pagetop.fadeIn();
       } else {
            pagetop.fadeOut();
            }
       });
       pagetop.click(function () {
           $('body, html').animate({ scrollTop: 0 }, 500);
              return false;
   });
});
</script>
</div>

app/views/minirooms/_miniroomfavorite.html.erb
   <div class="favorite-btn">
   <% if user_signed_in? %>
      <% if @miniroom.favorited?(current_user) %>
    <%# # 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ %>
    <%= link_to miniroom_miniroomfavorites_path(@miniroom.id), method: :delete do %>
        <span style="color:red;">❤︎</span>
      <%= miniroom.miniroomfavorites.length %>
          <% end %>

       <% elsif @miniroom.favorited?(current_user) %>
      <%= link_to miniroom_miniroomfavorites_path(miniroom, miniroom.miniroomfavorites), class: "like-link", method: :delete, remote: true do %>
      <% end %>

       <%= miniroom.miniroomfavorites.length %>

       <% else %>
           <%# # 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ %>
    <%= link_to miniroom_miniroomfavorites_path(@miniroom.id), method: :post do %>
        <span>❤︎</span>
       <% end %>
        <%= miniroom.miniroomfavorites.length %>
       <% end %>
       <% end %>
</div>

app/views/minirooms/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
       <%= render partial: "form", locals: { miniroom: @miniroom } %>
    </div>
  </div>
</div>

app/views/minirooms/index.html.erb
<main class="main">
<%= form_with(url: search_minirooms_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
  <div class="inner">
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
       <%= render partial: 'miniroom', collection: @minirooms %> 
    </div>
  </div>
</main>

app/views/minirooms/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規ミニマル写真投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { miniroom: @miniroom } %>
    </div>
  </div>
</div>

app/views/minirooms/search.html.erb
<%= form_with(url: search_minirooms_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @minirooms.each do |miniroom| %>
    <%= render partial: "miniroom", locals: { miniroom: miniroom } %>
  <% end %>
</div>

app/views/minirooms/show.html.erb
<main class="main">
  <div class="inner">
    <div class="miniroom__wrapper">
      <p class="miniroom__hedding">
        <%= @miniroom.title %>
      </p>
      <%# <%= link_to "by #{@mini_room.user_id.nickname}", "/users/#{mini_room.user.id}", class: :mini_room__user %> 
      <% if user_signed_in? && current_user.id == @miniroom.user_id %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="miniroom__manage">
          <%= link_to "編集する", edit_miniroom_path(@miniroom.id), method: :get, class: :miniroom__btn %>
            <p class="or-text">or</p>
          <%= link_to "削除する", miniroom_path(@miniroom.id), method: :delete, class: :miniroom__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% end %>
      <div class="miniroom__image">
        <%= image_tag @miniroom.image %>
      </div>
      <div class="miniroom__body">
        <div class="miniroom__detail">
          <p class="detail__message">
            <%= @miniroom.concept %>
          </p>
        </div>
      </div>

<div id = "miniroomfavorite_<%= @miniroom.id %>">
  <%= render partial: "minirooms/miniroomfavorite", locals: { miniroom: @miniroom } %>
</div>
 </div>
  <div class="donation__comments">
      <% if user_signed_in? %>
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%= form_with model: [@miniroom, @miniroomcomment],local: true do |f|%>
            <div class="field">
          <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
        <% end %>
         <% end %>
        <ul class="comments_lists">
          <% @miniroomcomments.each do |miniroomcomment| %>
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
            <%= miniroomcomment.content %>
      <strong><%= link_to "(#{miniroomcomment.user.nickname})さん", "/users/#{miniroomcomment.user.id}", class: :comment_user %></strong>
            </li>
             <% end %>
        </ul>
      </div>
    </div>

  </div>
</main>