config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'users/index', to: 'users#index'
  root 'minirooms#index'
  # resources :users, only: [:new, :show]
  resources :users do
      resource :relationships, only: [:create, :destroy]
      get :followings, on: :member
      get :followers, on: :member
  end

  resources :minirooms do
  resource :miniroomfavorites, only: [:create, :destroy]
  resources :miniroomcomments, only: :create
  collection do
    get 'search'
  end
  end

  resources :donations do
    resources :receives, only: [:index, :new, :create]
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :category_id, presence: true
    validates :condition_id, presence: true
    validates :delivery_id, presence: true
    validates :region_id, presence: true
    validates :ship_id, presence: true
    validates :image, presence: true
    validates :size_id, presence: true
  
    belongs_to :user
    has_one_attached :image
    has_many :donation_rooms
    has_one :receive
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_users, through: :favorites, source: :user

    def self.search(search)
      if search != ""
        Donation.where('name LIKE(?)', "%#{search}%")
      else
        Donation.all
      end
    end

    def favorited?(user)
      favorites.where(user_id: user.id).exists?
   end
  
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :category
    belongs_to :condition
    belongs_to :delivery
    belongs_to :region
    belongs_to :ship
    belongs_to :size
  
    validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :condition_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :delivery_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :region_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :ship_id, numericality: { other_than: 1 , message: "can't be blank"}
    validates :size_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_donation, only: [:edit, :show, :update, :destroy]
    before_action :move_to_index, except: [:index, :show, :search]
  
    def index
      @donations = Donation.all.order("created_at DESC")
      @user = User.new
    end
  
    def new
      @donation = Donation.new
    end
  
    def create
      @donation = Donation.create(donation_params)
      if @donation.save
        redirect_to donations_path
      else
        render :new
      end
    end
  
    def edit
    if current_user.id != @donation.user.id || @donation.present?
    if current_user.id != @donation.user.id
        redirect_to donations_path
     end
    end
  end
  
    def update
    if @donation.update(donation_params)
      redirect_to donations_path
    else
      render :edit
    end
  end
  
  def destroy
    if @donation.destroy
      redirect_to donations_path
    else
      render :index
    end
  end
  
    def show
      @comment = Comment.new
      @comments = @donation.comments.includes(:user)
    end

    def search
      @donations = Donation.search(params[:keyword])
    end
  
    private
  
    def donation_params
      params.require(:donation).permit(:name, :description, :category_id, :condition_id, :delivery_id, :region_id, :ship_id, :image, :size_id).merge(user_id: current_user.id)
    end
  
    def set_donation 
      @donation = Donation.find(params[:id])
    end
  
    def move_to_index
      unless user_signed_in?
        redirect_to action: :index
      end
    end
  end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
   <div class="card__body">
 <div class='donation-img-content'>
 <%= link_to image_tag(donation.image, class: "donation-img" ), donation_path(donation.id), method: :get %> <br>
         <% if donation.receive.present? %>  
          <div class='out'>
            <span>あげちゃった!!</span>
          </div>
     <% end %> 

    <%= link_to donation.name, donations_path(donation.id), class: :card__title%><br>
 <%= link_to "/#{donation.user.nickname}さん❤️❤️❤️", "/users/#{donation.user.id}" , class: :card__user %>  
  </div>
<p class="pagetop"><a href="#wrap">▲</a></p>
<script>
$(document).ready(function() {
  var pagetop = $('.pagetop');
    $(window).scroll(function () {
       if ($(this).scrollTop() > 100) {
            pagetop.fadeIn();
       } else {
            pagetop.fadeOut();
            }
       });
       pagetop.click(function () {
           $('body, html').animate({ scrollTop: 0 }, 500);
              return false;
   });
});
</script>
</div>

app/views/donations/_favorite.html.erb
   <div class="favorite-btn">
   <% if user_signed_in? %>
      <% if @donation.favorited?(current_user) %>
    <%# # 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ %>
    <%= link_to donation_favorites_path(@donation.id), method: :delete do %>
        <span style="color:red;">❤︎</span>
      <%=donation.favorites.length %>
          <% end %>

       <% elsif @donation.favorited?(current_user) %>
      <%= link_to donation_favorites_path(donation, donation.favorites), class: "like-link", method: :delete, remote: true do %>
      <% end %>

       <%= donation.favorites.length %>

       <% else %>
           <%# # 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ %>
    <%= link_to donation_favorites_path(@donation.id), method: :post do %>
        <span>❤︎</span>
       <% end %>
        <%= donation.favorites.length %>
       <% end %>
       <% end %>
</div>

app/views/donations/edit.html.erb
<div class="donations-sell-contents">
  <header class="donations-sell-header"> 

  </header>
  <div class="donation-main">
    <h2 class="donation-title">商品の編集入力</h2>
    <%= form_with model: @donation, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"donation-image" %>
      </div>
    </div>


    <div class="donations-detail">
     <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
      <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"donation-sales-status"}) %>
      </div>
    </div>

    <div class="donations-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          着払い料金
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"select-box", id:"donation-size-fee"}) %>
      </div>
    </div>


    <div class="sell-btn-contents">
      <%= f.submit "差し上げます",class:"sell-btn" %>
      <%=link_to 'もどる', donations_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  <footer class="donations-sell-footer">
  </footer>
</div>

app/views/donations/index.html.erb
<div class='main'>
<%= form_with(url: search_donations_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<%= link_to new_donation_path, class: 'receive-btn' do %> 
 <span class='donation-btn-text'>差し上げます</span> 
 <% end %> 
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'donation', collection: @donations %>
    </div>

 </div>

app/views/donations/new.html.erb
<div class="donations-sell-contents">
  <header class="donations-sell-header"> 

  </header>
  <div class="donation-main">
    <h2 class="donation-title">商品の情報を入力</h2>
    <%= form_with model: @donation, local: true do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"donation-image" %>
      </div>
    </div>
 <div class="new-donations">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"donations-text", id:"donation-name", placeholder:"商品名", maxlength:"40" %>
      <div class="donations-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"donations-text", id:"donation-info", placeholder:"商品の説明" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <div class="donations-detail">
     <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
       <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"donation-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
      <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"donation-sales-status"}) %>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_id, Delivery.all, :id, :name, {}, {class:"select-box", id:"donation-shipping-fee-status"}) %>
                <div class="weight-bold-text">
          着払い料金
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"select-box", id:"donation-size-fee"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"donation-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ship_id, Ship.all, :id, :name, {}, {class:"select-box", id:"donation-scheduled-delivery"}) %>
      </div>
    </div>


    <div class="sell-btn-contents">
      <%= f.submit "差し上げます",class:"sell-btn" %>
      <%=link_to 'もどる', donations_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  <footer class="donations-sell-footer">
  </footer>
</div>

app/views/donations/search.html.erb
<%= form_with(url: search_donations_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @donations.each do |donation| %>
    <%= render partial: "donation", locals: { donation: donation } %>
  <% end %>
</div>

app/views/donations/show.html.erb
<%# 商品の概要 %>
<div class="donation-show">
  <div class="donation-box">
    <h2 class="name">
      <%= @donation.name %>
    </h2>
   <div class="donation-img-content"> 
      <%= image_tag @donation.image ,class:"donation-box-img" %>
       <% if @donation.receive.present? %> 
      <div class="out"> 
        <span>あげちゃった!!</span> 
      </div> 
       <% end %>
 
    <% if user_signed_in? && @donation.receive.nil? %>
    <% if current_user.id == @donation.user.id %>
    <%= link_to "商品の編集", edit_donation_path(@donation.id), method: :get, class: "donation-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", donation_path(@donation.id), method: :delete, class:"donation-destroy" %>
   <% else %>

    <%= link_to "『いただきます』", donation_receives_path(@donation.id) ,class:"donation-green-btn"%>

    <% end %> 
   <% end %> 
 

    <div class="donation-explain-box">
      <span><%= @donation.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-donation">出品者</th>
          <td class="detail-value"><%= @donation.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-donation">カテゴリー</th>
          <td class="detail-value"><%= @donation.category.name %></td>
        </tr>
        <tr>
          <th class="detail-donation">商品の状態</th>
          <td class="detail-value"><%= @donation.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-donation">配送料の負担</th>
          <td class="detail-value"><%= @donation.delivery.name %></td>
        </tr>
          <tr>
          <th class="detail-donation">着払い料金</th>
          <td class="detail-value"><%= @donation.size.name %></td>
        </tr>
        <tr>
          <th class="detail-donation">発送元の地域</th>
          <td class="detail-value"><%= @donation.region.name %></td>
        </tr>
        <tr>
          <th class="detail-donation">発送日の目安</th>
          <td class="detail-value"><%= @donation.ship.name %></td>
        </tr>
      </tbody>
    </table>


    <div id = "favorite_<%= @donation.id %>">
     <%= render partial: "donations/favorite", locals: { donation: @donation } %>
   </div>
 </div>
  <div class="donation__comments">
      <% if user_signed_in? %>
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%= form_with model: [@donation, @comment],local: true do |f|%>
            <div class="field">
          <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
        <% end %>
         <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
            <%= comment.content %>
      <strong><%= link_to "(#{comment.user.nickname})さん", "/users/#{comment.user.id}", class: :comment_user %></strong>
            </li>
             <% end %>
        </ul>
      </div>
    </div>
    </div>

</div>